/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hSmcsWKw3zCBXehRUPYvUE

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantskodBJbKPhqSc } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: kodBJbKPhqSC/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantskodBJbKPhqSc
});
